// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int number = Integer.parseInt(args[0]);
		int upper = 0, lower = 0;
		for (int i = 0; i < number; i++){
			double random = Math.random();
				if (random < 0.5) {
					lower += 1;
				}else{
					upper += 1;
			}
		}
		double ratio = 0;
		if (upper > lower){
			ratio = lower / (double) upper;
		}else{ 	
			ratio = upper / (double) lower;
		}
		System.out.println("> 0.5		" + upper);
		System.out.println("< 0.5		" + lower);
		System.out.println("Ratio:		" + ratio);


	}
}
